apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: np-connect
spec:
  selector:
    matchLabels:
      app: np-connect
  template:
    metadata:
      labels:
        app: np-connect
    spec:
      containers:
      - name: node-app
        image: localhost:5000/nodetest:v1
        ports:
        - containerPort: 9999
---
kind: Service
apiVersion: v1
metadata:
  name: node-service
  labels:
    app: np-connect
spec:
  selector:
    app: np-connect
  ports:
  - port: 80
    targetPort: 9999

